convert-shls:
    paths:
        - "sl-comp/qf_shls_sat"
        - "sl-comp/qf_shls_entl"
    options:
        - "--pure-imprecise"
    to:
        - "astral"
        - "sloth"
        - "songbird"
        - "s2s"

convert-shlid:
    paths:
        - "sl-comp/qf_shlid_entl"
    matching: ".*dll.*"
    options:
        - "--pure-imprecise"
    to:
        - "astral"
        - "songbird"
        - "s2s"

convert-random:
    paths: ["random"]
    to: ["s2s"]
