# Configuration of solvers
#
# Mandatory arguments are:
#
#   - bin : name of the executable
#
# The optional arguments are:
#
#   - input-format : input format (default is .smt2)
#   - benchmarks : subdirectory in benchmarks/; set if the tool uses preprocessed benchmarks
#   - workdir: set if the tool needs to be run from a specific directory

astral:
  bin: astral

cvc5:
  bin: cvc5

grasshopper:
  bin: grasshopper.native
  workdir: solvers/bin/grasshopper
  input-format: .spl

harrsh:
  bin: harrsh

s2s:
  bin: s2s
  workdir: solvers/bin/s2s
  benchmarks: s2s
  input-format: .ss

sloth:
  bin: sloth.sh
  workdir: solvers/bin/sloth

songbird:
  bin: songbird
  workdir: solvers/bin/songbird
  benchmarks: songbird
  input-format: .sb

sls:
  bin: sls
  workdir: solvers/bin/sls
  benchmarks: songbird
  input-format: .sb


